nfe_dict={'nfeProc': {'@versao': '4.00',
             '@xmlns': 'http://www.portalfiscal.inf.br/nfe',
             'NFe': {'@xmlns': 'http://www.portalfiscal.inf.br/nfe',
                     'Signature': {'@xmlns': 'http://www.w3.org/2000/09/xmldsig#',
                                   'KeyInfo': {'X509Data': {'X509Certificate': 'MIIHcDCCBVigAwIBAgIMGOw6gWPo1SeBEASYMA0GCSqGSIb3DQEBCwUAMIGJMQswCQYDVQQGEwJCUjETMBEGA1UECgwKSUNQLUJyYXNpbDE2MDQGA1UECwwtU2VjcmV0YXJpYSBkYSBSZWNlaXRhIEZlZGVyYWwgZG8gQnJhc2lsIC0gUkZCMS0wKwYDVQQDDCRBdXRvcmlkYWRlIENlcnRpZmljYWRvcmEgU0VSUFJPUkZCdjUwHhcNMjIwNTEzMTIyMjA1WhcNMjMwNTEzMTIyMjA1WjCCAQoxCzAJBgNVBAYTAkJSMQswCQYDVQQIDAJTUDESMBAGA1UEBwwJUklPIENMQVJPMRMwEQYDVQQKDApJQ1AtQnJhc2lsMRMwEQYDVQQLDApwcmVzZW5jaWFsMRcwFQYDVQQLDA4xOTg2MDEyOTAwMDEwNjE2MDQGA1UECwwtU2VjcmV0YXJpYSBkYSBSZWNlaXRhIEZlZGVyYWwgZG8gQnJhc2lsIC0gUkZCMREwDwYDVQQLDAhBUkNFUlRGWTEWMBQGA1UECwwNUkZCIGUtQ05QSiBBMTE0MDIGA1UEAwwrTFVaIExFRCBDT01FUkNJTyBPTkxJTkUgTFREQTo0NjM2NDA1ODAwMDExNTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALHHzLy5Xid+d5/W6J8DzCXCtKX+aAPBz/hM7YGDFhoutcWyaviKin3o4xGEMe+Ja0jBt0jYtPOVUQLipqg3s+jJI76OizG2iOmzeLSHeLSpi6sm9m7Xg2HrgDIpOVvhXLd1ps1nGgE4Ghf/X6q2EtdnXr4+Wr0ANczyavUmtpSgW6W4SteXOf8AgR32badYXlyXCor5cxz6JoCikdbJmwrpV7m3Ph7MMZWXhMP/ovvafIeK5KF+5lSW46iVnrrmtRQGspRNJS1aFB9gKVrk2WBtRlMtw6n4yH2opT1zIQW9m4Fh+B6/3hkg6HQdnwqNzCpZ2cFO5ZO9qpjMI9q5a+cCAwEAAaOCAlIwggJOMB8GA1UdIwQYMBaAFBSALZ1+mkXA8Vs/GdVAsG8vZeDpMIGIBgNVHR8EgYAwfjA8oDqgOIY2aHR0cDovL3JlcG9zaXRvcmlvLnNlcnByby5nb3YuYnIvbGNyL2Fjc2VycHJvcmZidjUuY3JsMD6gPKA6hjhodHRwOi8vY2VydGlmaWNhZG9zMi5zZXJwcm8uZ292LmJyL2xjci9hY3NlcnByb3JmYnY1LmNybDBWBggrBgEFBQcBAQRKMEgwRgYIKwYBBQUHMAKGOmh0dHA6Ly9yZXBvc2l0b3Jpby5zZXJwcm8uZ292LmJyL2NhZGVpYXMvYWNzZXJwcm9yZmJ2NS5wN2IwgbsGA1UdEQSBszCBsKA4BgVgTAEDBKAvBC0wOTAxMTk5NzEyMTUwNjkzNjc0MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDCgIQYFYEwBAwKgGAQWTUFSQ0lPIEZFUlJFSVJBIENFQ0FUT6AZBgVgTAEDA6AQBA40NjM2NDA1ODAwMDExNaAXBgVgTAEDB6AOBAwwMDAwMDAwMDAwMDCBHWNlcnRpZmljYWRvLjNzZmFybWFAZ21haWwuY29tMA4GA1UdDwEB/wQEAwIF4DAdBgNVHSUEFjAUBggrBgEFBQcDBAYIKwYBBQUHAwIwWwYDVR0gBFQwUjBQBgZgTAECAQowRjBEBggrBgEFBQcCARY4aHR0cDovL3JlcG9zaXRvcmlvLnNlcnByby5nb3YuYnIvZG9jcy9kcGNhY3NlcnByb3JmYi5wZGYwDQYJKoZIhvcNAQELBQADggIBACCG47wim52UfrEXfi91BD4RhXYPPqkuPY1uJ6hyujfZNdRcd125OhC8CgHmCgECdHHdsS0EKV6UzvoN+KpnudFhQEV/UaXv3BnKURm59930C2jntbhIrqs/dlgiQqGIg7r1U/nyb802/SKEqyYmof9hsG+3hpJlgVM5vEWe1+1y7QMBQPa/dejHgxtdHYTXGW9FKgbf5RS20Z30JitxFHCYyLY2HHgtzhEleI3yADUCu4AokWWQngAuZV9+hQV3EiriNZjX5mWU2ltrHf9ZfQJrczsirXlncD6FNApDSNvmvRVvLq7FA0zngLvocQtVfYe6Wi3hoRdttX8wlQ6sVio6hyGKaF6hUejZiT9zvKVfCcJXCK7BdiQhZcCCSPO7zH3jqWcIXvRme0v5wl6ggWdNcDMh1xPWsvKeOaKhyac5bVFXMVeusprcMQVTNq2DX1e18qyz7h9E/AwDrwLcGCvCCRgAHxwA3wTMsK7E/DdZ+HdfnYNRZu+zX9dB/Kc6BaPVIg1vxHf3d4AkQbhXgOEOoFZQmzqtFssNzRW5aP9og65BB000wpcIP/2CC3SuhUA8MjLp5yZE9Um55b6O4qi6ffYBXqINjM/g2u4n9sCX8ec3x2gdQJdnZh623r9Tgzkq68cB02eOa0vMRYYVN3wFokqhTBNpZYMdezDMXem1'}},
                                   'SignatureValue': 'bBTsldo2G/PZ9nRJoymIndMAPpbFAXSqBtMLrQg8JvVGmxWWioW/FMpklVxVUBHmbreFvl8ZL/MshYfA4f+HeM+ObS11tVndFBtJ2OqPwGpZdjp62m1cGcJesxPPuRANw1dVOoAhE5cJgR8NFtmFvYpMwM01h5RqcBK7r3g0Coa+MGt4EoRb2jQbjIj2TJ1hsWw9a7QYzDYTXhAHtEl+ZxNBmz82sCbEffMk2/y3rUL2e0Urv14tNhLjjLkzrY/Im7P1wcAY6THzmbWC90svtj/ubMWwDvuVdCqbcxA9vc/05kEipcnszfa/HUiENMGsIUUcrHHlnFd8jCFVaupWTw==',
                                   'SignedInfo': {'CanonicalizationMethod': {'@Algorithm': 'http://www.w3.org/TR/2001/REC-xml-c14n-20010315'},
                                                  'Reference': {'@URI': '#NFe35220946364058000115550010000001181700960501',
                                                                'DigestMethod': {'@Algorithm': 'http://www.w3.org/2000/09/xmldsig#sha1'},
                                                                'DigestValue': '6a6rc10a2VaplnZ++8awU+tkm4M=',
                                                                'Transforms': {'Transform': [{'@Algorithm': 'http://www.w3.org/2000/09/xmldsig#enveloped-signature'},
                                                                                             {'@Algorithm': 'http://www.w3.org/TR/2001/REC-xml-c14n-20010315'}]}},
                                                  'SignatureMethod': {'@Algorithm': 'http://www.w3.org/2000/09/xmldsig#rsa-sha1'}}},
                     'infNFe': {'@Id': 'NFe35220946364058000115550010000001181700960501',
                                '@versao': '4.00',
                                'compra': {'xPed': '2000004135257768'},
                                'dest': {'CPF': '64342972972',
                                         'enderDest': {'CEP': '85301050',
                                                       'UF': 'PR',
                                                       'cMun': '4113304',
                                                       'cPais': '1058',
                                                       'nro': '1920',
                                                       'xBairro': 'Centro',
                                                       'xCpl': 'casa',
                                                       'xLgr': 'Rua Quinze de '
                                                               'Novembro',
                                                       'xMun': 'Laranjeiras do '
                                                               'Sul',
                                                       'xPais': 'Brasil'},
                                         'indIEDest': '9',
                                         'xNome': 'Edivaldo Rodrigues'},
                                'det': [{'@nItem': '1',
                                         'imposto': {'COFINS': {'COFINSOutr': {'CST': '49',
                                                                               'pCOFINS': '0.00',
                                                                               'vBC': '146.40',
                                                                               'vCOFINS': '0.00'}},
                                                     'ICMS': {'ICMSSN102': {'CSOSN': '102',
                                                                            'orig': '2'}},
                                                     'ICMSUFDest': {'pFCPUFDest': '0.0000',
                                                                    'pICMSInter': '4.00',
                                                                    'pICMSInterPart': '100.0000',
                                                                    'pICMSUFDest': '0.0000',
                                                                    'vBCFCPUFDest': '146.40',
                                                                    'vBCUFDest': '146.40',
                                                                    'vFCPUFDest': '0.00',
                                                                    'vICMSUFDest': '0.00',
                                                                    'vICMSUFRemet': '0.00'},
                                                     'IPI': {'IPINT': {'CST': '53'},
                                                             'cEnq': '999'},
                                                     'PIS': {'PISOutr': {'CST': '49',
                                                                         'pPIS': '0.00',
                                                                         'vBC': '146.40',
                                                                         'vPIS': '0.00'}}},
                                         'prod': {'CEST': '2112200',
                                                  'CFOP': '6108',
                                                  'NCM': '94054900',
                                                  'cEAN': '6959291021093',
                                                  'cEANTrib': '6959291021093',
                                                  'cProd': '102110',
                                                  'indTot': '1',
                                                  'qCom': '15.0000',
                                                  'qTrib': '15.0000',
                                                  'uCom': 'MT',
                                                  'uTrib': 'MT',
                                                  'vProd': '146.40',
                                                  'vUnCom': '9.76',
                                                  'vUnTrib': '9.76',
                                                  'xPed': '200000413525776',
                                                  'xProd': 'MANG 5050 BCO '
                                                           'QUENTE 110V - '
                                                           'EURO'}},
                                        {'@nItem': '2',
                                         'imposto': {'COFINS': {'COFINSOutr': {'CST': '49',
                                                                               'pCOFINS': '0.00',
                                                                               'vBC': '18.50',
                                                                               'vCOFINS': '0.00'}},
                                                     'ICMS': {'ICMSSN102': {'CSOSN': '102',
                                                                            'orig': '2'}},
                                                     'ICMSUFDest': {'pFCPUFDest': '0.0000',
                                                                    'pICMSInter': '4.00',
                                                                    'pICMSInterPart': '100.0000',
                                                                    'pICMSUFDest': '0.0000',
                                                                    'vBCFCPUFDest': '18.50',
                                                                    'vBCUFDest': '18.50',
                                                                    'vFCPUFDest': '0.00',
                                                                    'vICMSUFDest': '0.00',
                                                                    'vICMSUFRemet': '0.00'},
                                                     'IPI': {'IPINT': {'CST': '53'},
                                                             'cEnq': '999'},
                                                     'PIS': {'PISOutr': {'CST': '49',
                                                                         'pPIS': '0.00',
                                                                         'vBC': '18.50',
                                                                         'vPIS': '0.00'}}},
                                         'prod': {'CFOP': '6108',
                                                  'NCM': '94054900',
                                                  'cEAN': '6909234002023',
                                                  'cEANTrib': '6909234002023',
                                                  'cProd': '5050',
                                                  'indTot': '1',
                                                  'qCom': '1.0000',
                                                  'qTrib': '1.0000',
                                                  'uCom': 'UN',
                                                  'uTrib': 'UN',
                                                  'vProd': '18.50',
                                                  'vUnCom': '18.50',
                                                  'vUnTrib': '18.50',
                                                  'xPed': '200000413525776',
                                                  'xProd': 'CONECTOR LED 5050 '
                                                           '- 110V/220V'}}],
                                'emit': {'CNPJ': '46364058000115',
                                         'CRT': '1',
                                         'IE': '587462103112',
                                         'enderEmit': {'CEP': '13500143',
                                                       'UF': 'SP',
                                                       'cMun': '3543907',
                                                       'cPais': '1058',
                                                       'fone': '1935571411',
                                                       'nro': '192',
                                                       'xBairro': 'Zona '
                                                                  'Central',
                                                       'xCpl': 'Sala 02',
                                                       'xLgr': 'Rua 7',
                                                       'xMun': 'Rio Claro',
                                                       'xPais': 'Brasil'},
                                         'xFant': 'LUZ LED DECOR',
                                         'xNome': 'LUZ LED COMERCIO ONLINE '
                                                  'LTDA'},
                                'entrega': {'CEP': '85301050',
                                            'CPF': '64342972972',
                                            'UF': 'PR',
                                            'cMun': '4113304',
                                            'nro': '1920',
                                            'xBairro': 'Centro',
                                            'xCpl': 'Casa',
                                            'xLgr': 'Rua Quinze de Novembro',
                                            'xMun': 'Laranjeiras do Sul',
                                            'xNome': 'EDIVALDO RAUL '
                                                     'RODRIGUESE'},
                                'ide': {'cDV': '1',
                                        'cMunFG': '3543907',
                                        'cNF': '70096050',
                                        'cUF': '35',
                                        'dhEmi': '2022-09-01T08:09:54-03:00',
                                        'dhSaiEnt': '2022-09-01T08:09:59-03:00',
                                        'finNFe': '1',
                                        'idDest': '2',
                                        'indFinal': '1',
                                        'indIntermed': '0',
                                        'indPres': '2',
                                        'mod': '55',
                                        'nNF': '118',
                                        'natOp': 'Venda de mercadorias',
                                        'procEmi': '0',
                                        'serie': '1',
                                        'tpAmb': '1',
                                        'tpEmis': '1',
                                        'tpImp': '1',
                                        'tpNF': '1',
                                        'verProc': 'Tiny ERP'},
                                'infAdic': {'infCpl': 'Ref. ao pedido numero '
                                                      '2000004135257768Endereco:  '
                                                      'casa<br />OC: '
                                                      '2000004135257768',
                                            'obsCont': {'@xCampo': 'CEPEntrega',
                                                        'xTexto': '85301050'}},
                                'pag': {'detPag': {'tPag': '90', 'vPag': '0'}},
                                'total': {'ICMSTot': {'vBC': '0.00',
                                                      'vBCST': '0.00',
                                                      'vCOFINS': '0.00',
                                                      'vDesc': '0.00',
                                                      'vFCP': '0.00',
                                                      'vFCPST': '0.00',
                                                      'vFCPSTRet': '0.00',
                                                      'vFCPUFDest': '0.00',
                                                      'vFrete': '0.00',
                                                      'vICMS': '0.00',
                                                      'vICMSDeson': '0.00',
                                                      'vICMSUFDest': '0.00',
                                                      'vICMSUFRemet': '0.00',
                                                      'vII': '0.00',
                                                      'vIPI': '0.00',
                                                      'vIPIDevol': '0.00',
                                                      'vNF': '164.90',
                                                      'vOutro': '0.00',
                                                      'vPIS': '0.00',
                                                      'vProd': '164.90',
                                                      'vST': '0.00',
                                                      'vSeg': '0.00'}},
                                'transp': {'modFrete': '0',
                                           'transporta': {'CNPJ': '20121850000155',
                                                          'IE': '492875457119',
                                                          'UF': 'SP',
                                                          'xEnder': 'Avenida '
                                                                    'das '
                                                                    'Nacoes '
                                                                    'Unidas, '
                                                                    '3003 - '
                                                                    'PARTE C',
                                                          'xMun': 'Osasco',
                                                          'xNome': 'MERCADO '
                                                                   'ENVIOS '
                                                                   'SERVICOS '
                                                                   'DE '
                                                                   'LOGISTICA '
                                                                   'LTDA'},
                                           'vol': {'esp': 'CAIXA',
                                                   'pesoB': '1.225',
                                                   'pesoL': '1.225',
                                                   'qVol': '1'}}}},
             'protNFe': {'@versao': '4.00',
                         'infProt': {'cStat': '100',
                                     'chNFe': '35220946364058000115550010000001181700960501',
                                     'dhRecbto': '2022-09-01T08:20:06-03:00',
                                     'digVal': '6a6rc10a2VaplnZ++8awU+tkm4M=',
                                     'nProt': '135221182085074',
                                     'tpAmb': '1',
                                     'verAplic': 'SP_NFE_PL009_V4',
                                     'xMotivo': 'Autorizado o uso da NF-e'}}}}
