{'NFe': {'@xmlns': 'http://www.portalfiscal.inf.br/nfe',
         'infNFe': {'@Id': '',
                    '@versao': '4.00',
                    'dest': {'CPF': '05032465496',
                             'enderDest': {'CEP': '57210000',
                                           'UF': 'AL',
                                           'cMun': '2706802',
                                           'cPais': '1058',
                                           'nro': '12',
                                           'xBairro': 'Pontal do Peba',
                                           'xLgr': 'Rua Da Serraria',
                                           'xMun': 'Piacabucu',
                                           'xPais': 'Brasil'},
                             'indIEDest': '9',
                             'xNome': 'Tecio Caetano dos santos'},
                    'det': {'@nItem': '1',
                            'imposto': {'COFINS': {'COFINSOutr': {'CST': '49',
                                                                  'pCOFINS': '0.00',
                                                                  'vBC': '0.00',
                                                                  'vCOFINS': '0.00'}},
                                        'ICMS': {'ICMS00': {'CST': '00',
                                                            'modBC': '1',
                                                            'orig': '2',
                                                            'pICMS': '4.00',
                                                            'vBC': '169.90',
                                                            'vICMS': '6.80'}},
                                        'IPI': {'IPINT': {'CST': '53'},
                                                'cEnq': '999'},
                                        'PIS': {'PISOutr': {'CST': '49',
                                                            'pPIS': '0.00',
                                                            'vBC': '0.00',
                                                            'vPIS': '0.00'}}},
                            'prod': {'CFOP': '6106',
                                     'NCM': '94053100',
                                     'cEAN': 'SEM GTIN',
                                     'cEANTrib': 'SEM GTIN',
                                     'cProd': 'CFOP6106',
                                     'indTot': '1',
                                     'qCom': '1.0000',
                                     'qTrib': '1.0000',
                                     'uCom': 'UN',
                                     'uTrib': 'UN',
                                     'vProd': '0.00',
                                     'vUnCom': '0.00',
                                     'vUnTrib': '0.00',
                                     'xProd': 'COMPLEMENTO DE ICMS'}},
                    'emit': {'CNPJ': '46364058000115',
                             'CRT': '3',
                             'IE': '587462103112',
                             'enderEmit': {'CEP': '13501560',
                                           'UF': 'SP',
                                           'cMun': '3543907',
                                           'cPais': '1058',
                                           'fone': '001935571411',
                                           'nro': '1513',
                                           'xBairro': 'Jardim Anhanguera',
                                           'xLgr': 'Avenida 59',
                                           'xMun': 'Rio Claro',
                                           'xPais': 'Brasil'},
                             'xFant': 'LUZ LED DECOR',
                             'xNome': 'LUZ LED COMERCIO ONLINE LTDA'},
                    'ide': {'NFref': {'refNFe': '35220946364058000115550020000015821744441368'},
                            'cDV': '2',
                            'cMunFG': '3543907',
                            'cNF': '74444136',
                            'cUF': '35',
                            'dhEmi': '2023-04-10T10:11:53-03:00',
                            'finNFe': '2',
                            'idDest': '2',
                            'indFinal': '1',
                            'indPres': '2',
                            'mod': '55',
                            'nNF': '2708',
                            'natOp': 'Complementar de ICMS (Serie 2)',
                            'procEmi': '0',
                            'serie': '2',
                            'tpAmb': '1',
                            'tpEmis': '1',
                            'tpImp': '1',
                            'tpNF': '1',
                            'verProc': 'Tiny ERP'},
                    'infAdic': {'infCpl': 'Conforme artigo 182 IV do RICMS, '
                                          'Nota fiscal complementar de ICMS '
                                          'referente a NF 1582 da serie 02 de '
                                          '01/09/2022.'},
                    'infRespTec': {'CNPJ': '15088992000128',
                                   'email': 'integracao@tiny.com.br',
                                   'fone': '05430558200',
                                   'xContato': 'Fernando'},
                    'pag': {'detPag': {'tPag': '90', 'vPag': '0'}},
                    'total': {'ICMSTot': {'vBC': '169.90',
                                          'vBCST': '0.00',
                                          'vCOFINS': '0.00',
                                          'vDesc': '0.00',
                                          'vFCP': '0.00',
                                          'vFCPST': '0.00',
                                          'vFCPSTRet': '0.00',
                                          'vFCPUFDest': '0.00',
                                          'vFrete': '0.00',
                                          'vICMS': '6.80',
                                          'vICMSDeson': '0.00',
                                          'vICMSUFDest': '0.00',
                                          'vICMSUFRemet': '0.00',
                                          'vII': '0.00',
                                          'vIPI': '0.00',
                                          'vIPIDevol': '0.00',
                                          'vNF': '0.00',
                                          'vOutro': '0.00',
                                          'vPIS': '0.00',
                                          'vProd': '0.00',
                                          'vST': '0.00',
                                          'vSeg': '0.00'}},
                    'transp': {'modFrete': '9',
                               'vol': {'pesoB': '0.000', 'pesoL': '0.000'}}}}}