from pprint import pp
from typing import Dict, TypedDict


nfe_xml = {'NFe': {'@xmlns': 'http://www.portalfiscal.inf.br/nfe',
         'infNFe': {'@Id': '',
                    '@versao': '4.00',
                    'dest': {'CNPJ': '13914933000136',
                             'enderDest': {'CEP': '13500190',
                                           'UF': 'SP',
                                           'cMun': '3543907',
                                           'cPais': '1058',
                                           'nro': '033',
                                           'xBairro': 'centro',
                                           'xLgr': 'Rua 6, 1674',
                                           'xMun': 'Rio Claro',
                                           'xPais': 'Brasil'},
                             'indIEDest': '9',
                             'xNome': 'MeuCPD Soluções Tecnológicas'},
                    'det': {'@nItem': '1',
                            'imposto': {'COFINS': {'COFINSOutr': {'CST': '49',
                                                                  'pCOFINS': '0.00',
                                                                  'vBC': '0.00',
                                                                  'vCOFINS': '0.00'}},
                                        'ICMS': {'ICMS00': {'CST': '00',
                                                            'modBC': '1',
                                                            'orig': '2',
                                                            'pICMS': '4.00',
                                                            'vBC': '0.90',
                                                            'vICMS': '6.40'}},
                                        'IPI': {'IPINT': {'CST': '53'},
                                                'cEnq': '999'},
                                        'PIS': {'PISOutr': {'CST': '49',
                                                            'pPIS': '0.00',
                                                            'vBC': '0.00',
                                                            'vPIS': '0.00'}}},
                            'prod': {'CFOP': '6108',
                                     'NCM': '94053100',
                                     'cEAN': 'SEM GTIN',
                                     'cEANTrib': 'SEM GTIN',
                                     'cProd': 'CFOP6106',
                                     'indTot': '1',
                                     'qCom': '1.0000',
                                     'qTrib': '1.0000',
                                     'uCom': 'UN',
                                     'uTrib': 'UN',
                                     'vProd': '0.00',
                                     'vUnCom': '0.00',
                                     'vUnTrib': '0.00',
                                     'xProd': 'COMPLEMENTO DE ICMS'}},
                    'emit': {'CNPJ': '46364058000115',
                             'CRT': '3',
                             'IE': '587462103112',
                             'enderEmit': {'CEP': '13500143',
                                           'UF': 'SP',
                                           'cMun': '3543907',
                                           'cPais': '1058',
                                           'fone': '1935571411',
                                           'nro': '192',
                                           'xBairro': 'Zona Central',
                                           'xLgr': 'Rua 7',
                                           'xMun': 'Rio Claro',
                                           'xPais': 'Brasil'},
                             'xFant': 'LUZ LED DECOR',
                             'xNome': 'LUZ LED COMERCIO ONLINE LTDA'},
                    'ide': {'NFref': {'refNFe': '35220846364058000115550010000001161698381017'},
                            'cDV': '2',
                            'cMunFG': '3543907',
                            'cNF': '69838101',
                            'cUF': '35',
                            'dhEmi': '2023-04-06T16:55:13-03:00',
                            'finNFe': '2',
                            'idDest': '1',
                            'indFinal': '1',
                            'indPres': '2',
                            'mod': '55',
                            'nNF': '2820',
                            'natOp': 'Complementar de ICMS (Serie 1)',
                            'procEmi': '0',
                            'serie': '1',
                            'tpAmb': '1',
                            'tpEmis': '1',
                            'tpImp': '1',
                            'tpNF': '1',
                            'verProc': 'Tiny ERP'},
                    'infAdic': {'infCpl': 'Conforme artigo 182 IV do RICMS, '
                                          'Nota fiscal complementar de ICMS '
                                          'referente a NF 116 da serie 01 de '
                                          '31/08/2022.'},
                    'infRespTec': {'CNPJ': '15088992000128',
                                   'email': 'integracao@tiny.com.br',
                                   'fone': '05430558200',
                                   'xContato': 'Fernando'},
                    'pag': {'detPag': {'tPag': '90', 'vPag': '0'}},
                    'total': {'ICMSTot': {'vBC': '159.90',
                                          'vBCST': '0.00',
                                          'vCOFINS': '0.00',
                                          'vDesc': '0.00',
                                          'vFCP': '0.00',
                                          'vFCPST': '0.00',
                                          'vFCPSTRet': '0.00',
                                          'vFCPUFDest': '0.00',
                                          'vFrete': '0.00',
                                          'vICMS': '6.40',
                                          'vICMSDeson': '0.00',
                                          'vICMSUFDest': '0.00',
                                          'vICMSUFRemet': '0.00',
                                          'vII': '0.00',
                                          'vIPI': '0.00',
                                          'vIPIDevol': '0.00',
                                          'vNF': '0.00',
                                          'vOutro': '0.00',
                                          'vPIS': '0.00',
                                          'vProd': '0.00',
                                          'vST': '0.00',
                                          'vSeg': '0.00'}},
                    'transp': {'modFrete': '9',
                               'vol': {'pesoB': '0.000', 'pesoL': '0.000'}}}}
                               }['NFe']['infNFe']
